                                                                          
apiVersion: v1                                                            
kind: Pod                                                                 
metadata:                                                                 
  name: redis-app-pod # Improved, more descriptive name                   
  labels:                                                                 
    app: redis-app                                                        
    environment: development # Example label                              
    tier: cache          # Example label                                  
spec:                                                                     
  restartPolicy: OnFailure # Changed from Never, consider if a Deployment is more suitable                                                            
  securityContext: # Pod-level security context                           
    runAsNonRoot: true                                                    
    runAsUser: 1001      # Example non-root UID                           
    runAsGroup: 1001     # Example non-root GID                           
    fsGroup: 1001        # Ensures volume permissions are set for the user/group                                                                  
  containers:                                                             
  - name: redis-container # Improved, more descriptive container name     
    image: redis:7.2.4    # Specific image version                        
    ports:                                                                
    - containerPort: 6379 # Expose Redis port (informational)             
    env:                                                                  
    # Avoid using environment variables for secrets if possible.          
    # If absolutely necessary and secrets are simple strings, this is how,
    # but volume mounts are preferred (see below).                        
    # For demonstration of secure practice, we will remove these and use volume mounts.                                                              
    # - name: SOME_OTHER_CONFIG                                           
    #   value: "some_value"                                               
    resources:                                                            
      requests:                                                           
        memory: "128Mi"                                                   
        cpu: "100m" # 0.1 CPU core                                        
      limits:                                                             
        memory: "256Mi"                                                   
        cpu: "200m"  # 0.2 CPU core                                       
    securityContext: # Container-level security context                   
      allowPrivilegeEscalation: false                                     
      capabilities:                                                       
        drop:                                                             
        - ALL                                                             
      # readOnlyRootFilesystem: true # Enable if your application supports it                                                                          
                                   # Redis might need writable paths, consider /data volume                                                       
    volumeMounts:                                                         
    - name: secret-volume                                                 
      mountPath: "/etc/secrets" # Mount path for the secret               
      readOnly: true                                                      
    # If Redis needs a writable directory for data persistence (and it's not ephemeral)                                                              
    # - name: redis-data                                                  
    #   mountPath: /data                                                  
    livenessProbe:                                                        
      tcpSocket:                                                          
        port: 6379                                                        
      initialDelaySeconds: 15                                             
      periodSeconds: 20                                                   
      failureThreshold: 3                                                 
    readinessProbe:                                                       
      exec: # More robust check for Redis                                 
        command:                                                          
        - redis-cli                                                       
        - -h                                                              
        - "127.0.0.1" # Connect to localhost within the Pod               
        - -p                                                              
        - "6379"                                                          
        - ping                                                            
      initialDelaySeconds: 5                                              
      periodSeconds: 10                                                   
      timeoutSeconds: 5                                                   
      successThreshold: 1                                                 
      failureThreshold: 3                                                 
  volumes:                                                                
  - name: secret-volume                                                   
    secret:                                                               
      secretName: mysecret1 # Name of the Secret to mount                 
  # If you need persistent storage for Redis data or a writable directory:
  # - name: redis-data                                                    
  #   emptyDir: {} # Or a persistentVolumeClaim for production     