                                                                          
apiVersion: v1                                                            
kind: Pod                                                                 
metadata:                                                                 
  name: app-livenessprob-improved                                         
  namespace: demo                                                         
  labels:                                                                 
    app: my-app                                                           
    environment: demo                                                     
spec:                                                                     
  containers:                                                             
  - name: app                                                             
    image: gcr.io/smartcity-gl/demo:v1.0.1                                
    ports:                                                                
    - containerPort: 8080                                                 
      name: http                                                          
      protocol: TCP                                                       
    livenessProbe:                                                        
      httpGet:                                                            
        path: /healthz # Consider a dedicated health check endpoint       
        port: http # Use the named port for clarity and flexibility       
      initialDelaySeconds: 15 # Increased slightly to give more startup   time                                                                        
      periodSeconds: 10                                                   
      timeoutSeconds: 2 # Slightly increased for network hiccups          
      failureThreshold: 3                                                 
      successThreshold: 1                                                 
    readinessProbe:                                                       
      httpGet:                                                            
        path: /readyz # Consider a dedicated readiness endpoint           
        port: http # Use the named port                                   
      initialDelaySeconds: 5                                              
      periodSeconds: 5                                                    
      timeoutSeconds: 2                                                   
      failureThreshold: 3                                                 
      successThreshold: 1                                                 
    resources:                                                            
      requests:                                                           
        memory: "64Mi"                                                    
        cpu: "250m" # 0.25 CPU cores                                      
      limits:                                                             
        memory: "128Mi"                                                   
        cpu: "500m" # 0.5 CPU cores                                       
    securityContext:                                                      
      allowPrivilegeEscalation: false                                     
      capabilities:                                                       
        drop:                                                             
        - ALL                                                             
      # It's highly recommended to run as a non-root user.                
      # You'll need to ensure your container image supports this.         
      # runAsNonRoot: true                                                
      # runAsUser: 1000 # Example non-root user ID                        
      # runAsGroup: 1000 # Example non-root group ID                      
      readOnlyRootFilesystem: true # If your application supports it      
  # Pod level security context can also be applied                        
  # securityContext:                                                      
  #   runAsNonRoot: true                                                  
  #   fsGroup: 1000 # If using volumes